name: Integration Tests

on:
  push:
    branches: [main, rc]
  pull_request:
    branches: "**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run in docker
        run: |
          docker build . -t pocketbase-typegen:latest
          docker run pocketbase-typegen:latest
